# Sudoku usando Backtracking and heuristica MRV
Algoritmo de búsqueda con la heurística MRV (Minimum Remaining Values). El cual prioriza las celdas con menos valores posibles para optimizar el proceso de búsqueda.

Pasos:
Identifica las celdas vacías.
Verifican números posibles en cada celda basada en las reglas del Sudoku.
backtracking con la heurística MRV.

Integrantes:
- Mauricio Jaramillo
- Diego Oporto
- Francisco Sanhueza
- Abner Villanueva

In [2]:
import numpy as np
import time

class Sudoku:
    def __init__(self, puzzle):
        self.puzzle = puzzle
        self.size = 9

    def is_valid(self, fila, col, num):
        "Verifica si es válido colocar num en la celda (row, col)."
        # Verificar la fila
        for i in range(self.size):
            if self.puzzle[fila][i] == num:
                return False

        # Verificar la columna
        for i in range(self.size):
            if self.puzzle[i][col] == num:
                return False

        # Verificar la caja de 3x3
        caja_fila = fila - fila % 3
        caja_columna = col - col % 3
        for i in range(3):
            for j in range(3):
                if self.puzzle[caja_fila + i][caja_columna + j] == num:
                    return False
        return True

    def buscar_celda_vacia(self):
        "Encuentra la celda vacía con menos valores posibles con heurística MRV"
        min_options = 10
        empty_cell = None
        for row in range(self.size):
            for col in range(self.size):
                if self.puzzle[row][col] == 0:
                    options = self.obtener_valores_posibles(row, col)
                    if len(options) < min_options:
                        min_options = len(options)
                        empty_cell = (row, col)
        return empty_cell

    def obtener_valores_posibles(self, row, col):
        "Devuelve los posibles valores que se pueden colocar en la celda (row, col)."
        possible_values = []
        for num in range(1, 10):
            if self.is_valid(row, col, num):
                possible_values.append(num)
        return possible_values

    def solve(self):
        "Resuelve el Sudoku usando Backtracking con heurística MRV."
        empty_cell = self.buscar_celda_vacia()
        if not empty_cell:
            return True  # No hay celdas vacías, el Sudoku está resuelto
        row, col = empty_cell
        for num in self.obtener_valores_posibles(row, col):
            self.puzzle[row][col] = num
            if self.solve():
                return True
            self.puzzle[row][col] = 0  # Deshacer la asignación
        return False


# Sudoku 

puzzle = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0]
]

solver = Sudoku(puzzle)

tiempo_inicio = time.time()
solver.solve()
tiempo_final = time.time()

print("Sudoku Resuelto:")
print(np.array(solver.puzzle))
print(f"Tiempo de resolución: {tiempo_final - tiempo_inicio:.4f} segundos")



Sudoku Resuelto:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 3 1 6 7 4 8 9 5]
 [8 7 5 9 1 2 3 6 4]
 [6 9 4 5 3 8 2 1 7]
 [3 1 7 2 6 5 9 4 8]
 [5 4 2 8 9 7 6 3 1]
 [9 6 8 3 4 1 5 7 2]]
Tiempo de resolución: 0.0739 segundos
